[build]
bin = "./tmp/main"
cmd = "go build -o ./tmp/main.exe  ./server/cmd/app"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor"]
exclude_file = ["air.toml"]

[log]
level = "debug"

[directories]
watch = ["./server"]